baseURL: https://poyasharonlin.github.io/website/
languageCode: en-us
build:
  writeStats: true
params:
  title: PoYaSharon Lin
  author: PoYaSharon Lin
  description: Personal website of PoYaSharon Lin
  copyright: >-
    Deployed on [GitHub Pages](https://pages.github.com/) 
  theme:
    mainTheme: light
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Po-Ya, Lin"
    # tagline: "National Tsing Hua University"
    location: "Hsin Chu, Taiwan"
    photo: profile.jpg
  social:
    title: Links
    list:
      # - icon: fab fa-linkedin-in
      #   url: "#"
      #   title: LinkedIn
      # - icon: fab fa-stack-overflow
      #   url: "#"
      #   title: StackOverflow
      - icon: fab fa-github
        url: "https://github.com/PoYaSharonLin"
        title: GitHub
      # - icon: fab fa-twitter
      #   url: "#"
      #   title: Twitter
      - icon: fab fa-orcid
        url: "https://orcid.org/0009-0002-7468-1526"
        title: Orcid
      # - icon: ai ai-google-scholar
      #   url: "#"
      #   title: Google Scholar
      # - icon: fab fa-researchgate
      #   url: "#"
      #   title: ResearchGate
  showInAccordion:
    - item: education
    - item: aboutme
      expand: true
  aboutme:
    title: About Me
    icon: fas fa-user
    description: |
      I am a MBA student from National Tsing Hua University, Taiwan, interested in natural language understanding, multimodal signal processing, 
      and human behavior modeling — driven by a core question: how do different signals encode meaning?, 
      and how can we detect when that meaning is accurate? My research interests leads me to journeys empassing 
      semantic analysis, satellite image, and biosignal analysis. 

      I am now seeking a PhD position in Information System where I can contribute to the 
      detection of self-reporting data, 
      bringing together my background in multimodal signal processing, behavioral trace data, and 
      applied machine learning. 

  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Customer Support AI Chat Intern
        dates: 2022/07 - 2022/09
        company: Hotai Motor
        details: |1-
          - Improved AI Chatbot model performance from **95\% to 97\%** after implementing the following adjustments
          - N-gram analysis for the "complaint" category using **Antconc** and applying **Name Entity Recognition**
          - Added multi-condition complaint detection by retraining customers' requests about the frequent malfunction of components
      # - position: Job Title
      #   dates: 2018 - 2019
      #   url: "#"
      #   company: Company Name
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      # - degree: Ph.D. in Subject
      #   college: University of State-City
      #   dates: 2013 - 2018
        # thesis_title: "Intention Understanding: Using Knowledge Graph and Stakeholders map to improve computer pragmatic understanding"
      #   thesis_url: "#"
      - degree: MBA in Technology Management
        college: National Tsing Hua University, Taiwan
        dates: 2024 - Present
        logo: https://www.nthu.edu.tw//public/images/about10/cis-1-1.jpg
        thesis_title: "Reducing Misreporting of Health Information through Novel Positive Appeals. Evidence from Mouse-Tracking Recognition"
        # thesis_url: "#"
        description:
      - degree: Exchange Student in Department of Technology Management
        college: Technical University of Munich, Germany
        dates: Apr - Sept 2023
        logo: "https://github.com/iwb.png?size=256"
        description: |
          • German Scale: 1.3 (3.9/4.0 GPA)

          • Relevant Coursework: Business Analytics (A/A+), Reinforcement Learning (A/A+)
      - degree: B.A. in Foreign Language and Literature
        college: National Cheng Kung University, Taiwan
        dates: 2019 - 2024
        logo: https://web.ncku.edu.tw/var/file/0/1000/img/1215/ncku-logo1.jpg
        thesis_title: "Hybrid Electric Vehicle Sales Prediction: Using ANN, ANFIS, and Electronic Word of Mouth"
        # thesis_url: "https://drive.google.com/file/d/1kPSxWki2qHDU6GOjUp6GFk7taJx2MCSV/view?usp=sharing"
        description: |
          The thesis aims to evaluate how well the search volume and the overall sentiment score of posts on a Mandarin online mobile forum would affect the prediction of sales of hybrid electric vehicles. <br><br>
          The result revealed that the electronic Word-of-mouth data does not substantially improve the sales prediction of Hybrid Electric Vehicle.
  # experience:
  #   title: Experiences
  #   icon: fas fa-briefcase
  #   list:
  #     - position: Job Title
  #       dates: 2018 - 2019
  #       company: Company Name
  #       details: |1-
  #         - Description of the job
  #         - Description of the job
  #     - position: Job Title
  #       dates: 2018 - 2019
  #       company: Company Name
  #       details: |1-
  #         - Description of the job
  #         - Description of the job
  # education:
  #   title: Education
  #   icon: fas fa-graduation-cap
  #   list:
  publication:
    title: Research
    icon: fas fa-book
    list:
      - title: "Hybrid Electric Vehicle Sales Prediction using ANN, ANFIS, and E-Word-of-Mouth"
        # url: "https://drive.google.com/file/d/1kPSxWki2qHDU6GOjUp6GFk7taJx2MCSV/view?usp=sharing"
        description: |
          • Achieved highest accuracy with ANFIS model incorporating E-WOM sentiment and volume features
          
          • Demonstrated significant forecasting improvements via social media signal integration
          
          • NSTC 112-2813-C-006-026-H 2
  project:
    title: Projects
    icon: fas fa-project-diagram
    sections:
      - section: Textual Analysis
        list:
          - title: Electronic Direct Mail Precision Marketing
            # url: "https://drive.google.com/file/d/1ZYTvsvyhrtboKDprvE_tktB-VFKohbBz/view?usp=sharing"
            description: |
              • Utilized XGBoost to predict subscription likelihood based on user information and behavior. <br><br>

              • Used SMOTE to handle data imbalance. <br><br>

              • Leveraged **BERT** to assess the likelihood of an **email subject** line leading to an unsubscription. <br><br>
      - section: Image Analysis
        list:
          - title: Satellite Cloud Image prediction using ConvLSTM
            url: "https://drive.google.com/file/d/1sH8mLJBQgHYu6ajCrAUo0TlqGPwIRViq/view"
            description: |1-
              • Applied **ConvLSTM to predict the movement of the infrared cloud image** and used MAE, MSE, SSIM, PSNR as performance evaluation. <br><br>

              • Compared to ConLSTM, Self-attention LSTM may not be as effective as expected due to the characteristics of cloud cluster movement. <br><br>
              (only moves around one specific local area at 10-minute intervals.) <br><br>
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "Python"
        skillrating: 60
      - skill: Hugo(Go)
        skillrating: 40
      - skill: NextJS(Typescript)
        skillrating: 30
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Cooking
      - hobby: Baking
